apiVersion: v1
kind: Pod
metadata:
  name: flask-webapp-configmap
  labels:
    name: flaskapp
spec:
  containers:
    - name: flask-configmap
      image: flask-configmap
      imagePullPolicy: Never
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
      ports:
        - containerPort: 5000
          hostPort: 5000
          name: app-port
      env:
        - name: DISH_NAME
          valueFrom:
            configMapKeyRef:
              name: restaurant-config
              key: dish_of_the_day
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
data:
  # property-like keys
  dish_of_the_day: "spaghetti alla carbonara"
  dessert_of_the_day: "ice cream"
