apiVersion: v1
kind: Pod
metadata:
  name: flask-webapp-configmap
  labels:
    name: flaskapp
spec:
  containers:
    - name: flask-configmap
      image: flask-configmap
      imagePullPolicy: Never
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
      ports:
        - containerPort: 5000
          hostPort: 5000
          name: app-port
      envFrom:
        - configMapRef:
            name: restaurant-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
data:
  # property-like keys
  DISH_NAME: "tikka masala"
  DESSERT: "mango lassi"
